### ISSUE TITLE
HTTPS architecture 

### ISSUE THREAD

**Issue by mira1991** [Alfresco/alfresco-ansible-deployment#170]
What are the needed changes in the ansible playbooks to make alfresco community runs on 443 port ?

I tried to change only the configuration of nginx, but it looks like there are some other changes to be made to the tomcat config on  server.xml and alfresco-global.properties.

**Comment by alxgomz** [comment]
Yes for now HTTPS is not yet supported in the alfresco-ansible-deployment tool. The easiest way to configure it is probably to setup SSL offloading at the NGINX level but that means the proxy kind of masquerade the tomcat config. That indeed require some configuration tweaks depending on which part of the product you use.
The documentation bellow address that exact topic. I hope it'll help you:

**Comment by gavincornwell** [comment]
The ability to configure HTTPS/SSL is on the backlog (https://alfresco.atlassian.net/browse/OPSEXP-850) to be implemented in a future release.
