### ISSUE TITLE
cannot deploy on ubuntu 20.04 distribution.

### ISSUE THREAD

**Issue by shawnggraham** [Alfresco/alfresco-ansible-deployment#182]
I need a production installation of alfresco community addition and do not get very good performance out of the docker builds (im also just not a very big fan of docker).  I wanted to try the Ansible scripts but there is no playbook for Ubuntu 20.04 When i try and follow the installation notes i get this error (see attached).
![image](https://user-images.githubusercontent.com/4341130/114316806-05648380-9aba-11eb-9385-7de7c81a864b.png)

**Comment by gavincornwell** [comment]
Hi @shawnggraham Unfortunately the playbooks do not work with Ubuntu yet, as you can see here https://github.com/Alfresco/alfresco-ansible-deployment/blob/master/docs/README.md#versioning we currently only test with CentOS and RedHat. Ubuntu support is on the roadmap though so please keep an eye on the repository for updates.

**Comment by fgjohnson** [comment]
There seems to be Ubuntu support now.
But I can't get it to work.
Perhaps I am missing appropriate prerequisites... got a list?

Activemq and Libreoffice fail to install and the services don't start,.
