### ISSUE TITLE
OnlyOffice Issue?

### ISSUE THREAD

**Issue by heretech373** [Alfresco/alfresco-ansible-deployment#191]
Hey, after installing Alfresco via Ansible  I've got a strange situation with OnlyOffice integration.
It's all done by the book, but I'm getting 

`ERROR [web.context.ContextLoader] [main] Context initialization failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'patch.updateAdminUserWhenDefault' defined in URL [jar:file:/var/opt/alfresco/tomcat/webapps/alfresco/WEB-INF/lib/alfresco-repository-8.423.jar!/alfresco/patch/patch-services-context.xml]: Invocation of init method failed; nested exception is org.springframework.beans.factory.BeanDefinitionStoreException: Invalid bean definition with name 'transformer.onlyoffice' defined in URL [jar:file:/var/opt/alfresco/tomcat/webapps/alfresco/WEB-INF/lib/onlyoffice-integration-repo.jar!/alfresco/extension/onlyoffice-context.xml]: Could not resolve parent bean definition 'baseContentTransformer'; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'baseContentTransformer' available
`

I'm not sure where to look at

**Comment by alxgomz** [comment]
Can you give more information on what the only office integration involves and how you did it?
Did the system worked OK prior to do the only office integration?

**Comment by heretech373** [comment]
I've got 2 Alfresco installations, 5.2 Community and 7.0 Community.
OnlyOffice Document Server was integrated as instructed in https://api.onlyoffice.com/editors/alfresco.

It works fine with 5.2 but shows error when trying to add jar-files to 7.0 server.

**Comment by alxgomz** [comment]
As per the onlyooffice doc site they do not claim ACS 7 compatibility.
The Ansible playbook doesn't provides for now a way to automatically apply amps so I would argue that this not really an issue for the alfresco ansible playbook... as long as the deployed Alfresco intance works after play and before integration of onlyoffice AMP.
