### ISSUE TITLE
I cant' open alfresco content application

### ISSUE THREAD

**Issue by Bers12** [Alfresco/alfresco-ansible-deployment#193]
Hello!I installed alfresco using ansble method of installation from this site
https://docs.alfresco.com/content-services/community/install/ansible/

When i open it in browser-there is no alfresco content application.
There is a blank window.But there should be identification window to alfresco content application.
I can enter alfresco using this link 192.168.1.161/share.But i also need alfresco content application.
How can i switch on or install alfresco content application ?This is sharing files in alfresco.
You can see on the first picture where i have no window with alfresco content application.
And on the second picture i have window with alfresco content application .I installed alfresco with docker.
But i need this application with ansible method of installation.
![alfa](https://user-images.githubusercontent.com/87566544/126726835-925809e8-a015-4b6c-bd0f-b28f8c4f5406.jpg)
![al2](https://user-images.githubusercontent.com/87566544/126726849-f4ee43c6-6827-435f-b6b0-0cb048451b89.jpg)

**Comment by alxgomz** [comment]
ADW or ACA should be available under /worskpace/ not /. Using / is a docker-compose specificity

**Comment by Bers12** [comment]
alxgomz So how can i switch on alfresco content application or could you give me the right link to open it ?
I instaled it on server with ip address 192.168.184.161
I just installed alfresco using ansible method from this site and can't open it.https://docs.alfresco.com/content-services/community/install/ansible/

**Comment by Bers12** [comment]
I enter 192.168.184.161 .And there is blacnk page with inscription 
Online Documentation
Alfresco Repository

And there is no alfresco conten application identification window to enter it.
I can open alfresco using link 192.168.184.161/share.
But i need the link to alfresco content application or swtich it on to join it.

**Comment by alxgomz** [comment]
Our documentation below lists the different locations for the different applications:

[https://github.com/Alfresco/alfresco-ansible-deployment/blob/master/docs/deployment-guide.md#getting-started-quickly](https://github.com/Alfresco/alfresco-ansible-deployment/blob/master/docs/deployment-guide.md#getting-started-quickly):

Taking a second look it appears we only deploy ADW (Alfresco Digital Workspace - the enterprise version of the content App) but not ACA (the community version).

**Comment by Bers12** [comment]
So i should deploy aca additionaly and manually ?

**Comment by alxgomz** [comment]
yes indeed, for now you have to I'm afraid.
I have raised a ticket internally for us to track and will close this one as a consequence.
