### ISSUE TITLE
Include OS specific variables fails for Ubuntu

### ISSUE THREAD

**Issue by amthmsExprn** [Alfresco/alfresco-ansible-deployment#200]
The associated Ubuntu variables for the "Include OS specific variables" tasks do not exist. As such it deployment to Ubuntu environments will fail. Per the docs (https://github.com/Alfresco/alfresco-ansible-deployment/tree/master/docs) it should be supported.

**Example Task from roles/common/tasks/main.yml:**

```
# tasks file for central
- name: Include OS specific variables
  include_vars: "{{ ansible_distribution }}{{ ansible_distribution_major_version }}.yml"
```

Files for RHEL and CentOS exist (e.g., RedHat7.yml and CentOS7.yml). For Ubuntu 20.04, it looks for a Ubuntu20.yml files that do not exist in the deployment repo.

**Comment by amthmsExprn** [comment]
Issue may not to be in  this repo compared to the fork I was working out of. It looks like it should now be look for Debian.yml instead of Ubuntu20.yml. The fork I started from doesn't have the update in master. In checking here/upstream, I was looking for the associated Ubuntu20.yml files and did not see them. Will try to confirm before closing.

**Comment by alxgomz** [comment]
Hi @amthmsExprn ,

I remember testing that myself with ubuntu 18 & 20 so I'd indeed be surprised if a var file was missing.
Not sure which fork you are using but I'd encourage you using the official repo is that fits your needs.
Also please take in consideration Ubuntu support is available in master but no release has been made yet so should you find any issue with ubuntu support please add the failing task(s) logs software version and so on.

Can you confirm this is linked to your fork so I can close this issue?

**Comment by alxgomz** [comment]
closing issue as it remained without an update for a few days and I think there is no problem

**Comment by amthmsExprn** [comment]
Agree with closing. I checked the code, but I was not able to explicitly test it.
