### ISSUE TITLE
.sh files with setenv path hard coded

### ISSUE THREAD

**Issue by luisfernandezprado** [Alfresco/alfresco-ansible-deployment#219]
Hi,

It is detected that the following "sh" boot files have the path of the "setenv.sh" hard coded without using the ansible configuration path {{ config_folder }}.

The following change is proposed
```bash
## original
. /etc/opt/alfresco/setenv.sh
## change
. {{ config_folder }}/setenv.sh
```

Affected files
- alfresco-ansible-deployment\roles\sfs\templates\ats-shared-fs.sh
- alfresco-ansible-deployment\roles\sync\templates\syncservice.sh
- alfresco-ansible-deployment\roles\transformers\templates\ats-ate-aio.sh
- alfresco-ansible-deployment\roles\trouter\templates\ats-atr.sh

**Comment by howkymike** [comment]
Well, I also lost a few seconds to spot this mistake (and also wanted to PR this). I wonder why is it so complicated and long-lasting to fix such a small bug.

**Comment by gionn** [comment]
@luisfernandezprado @howkymike thanks for reporting! All of your concerns should have been addressed, plus some more.
