### ISSUE TITLE
Ansible split function doesn't work as intended

### ISSUE THREAD

**Issue by shankarasta** [Alfresco/alfresco-ansible-deployment#225]
Following line in roles/transformers/vars/Redhat8.yml 
imagemagick_home: "/usr/lib64/ImageMagick-{{ imagemagick_pkg.version.split('-')[0] }}"

results in 
imagemagick_home: "/usr/lib64/ImageMagick-[7.1.0-7]"
as opposed to imagemagick_home: "/usr/lib64/ImageMagick-7.1.0" as intended.

My ansible version is as follows:
ansible [core 2.11.6] 
  config file = None
  configured module search path = ['/home/ec2-user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/ec2-user/.local/lib/python3.6/site-packages/ansible
  ansible collection location = /home/ec2-user/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/ec2-user/.local/bin/ansible
  python version = 3.6.8 (default, Aug 12 2021, 07:06:15) [GCC 8.4.1 20200928 (Red Hat 8.4.1-1)]
  jinja version = 2.10.1
  libyaml = True

Using regex_replace I was able to fix this.
imagemagick_home: "/usr/lib64/ImageMagick-{{ imagemagick_pkg.version | regex_replace('-.+')}}

Thanks,
Shankar

**Comment by alxgomz** [comment]
Thanks for reporting that. This has actually been fixed in master by 
![image](https://user-images.githubusercontent.com/2311899/147914129-9ceeaaf6-b06f-4b1e-9547-27c751479704.png)
