### ISSUE TITLE
ERROR! 'notify' is not a valid attribute for a Block

### ISSUE THREAD

**Issue by MatthiasBauernberger** [Alfresco/alfresco-ansible-deployment#315]
Hi,

I tried alfresco-ansible-deployment v2.0 but got the following error (I tried it on two different machines; CentOS 7.9 and Oracle Linux 8.5).  I hope someone can give me hint to solve this problem. 

Thank you,
Matthias

PS.: Version v1.2.0 works flawless 

---------

```
ERROR! 'notify' is not a valid attribute for a Block

The error appears to be in '/opt/alfresco-ansible-deployment-2.0.0/roles/nginx/tasks/vhosts.yml': line 37, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


- name: Vhosts config
  ^ here
```

**Comment by gionn** [comment]
Hello Matthias, you are probably still using an outdated ansible version, we had to bump ansible version to 2.12 since 2.9 is going EOL in [May 2022](https://docs.ansible.com/ansible/devel/reference_appendices/release_and_maintenance.html#ansible-core-changelogs).

You can easily install the updated dependencies as described in the [deployment section](https://github.com/Alfresco/alfresco-ansible-deployment/blob/master/docs/deployment-guide.md#setup-a-control-node):

```
pip install -r requirements.txt
ansible-galaxy install -r requirements.yml
```

**Comment by MatthiasBauernberger** [comment]
Thank you for your quick response. I wasn't able to get the required prerequisites up n running on CentOS7 (pyhton, pip and ansible are too old and I found no way to upgrade this components). On Ubuntu 20 LTS I was able to execute alfresco-ansible-deployument (after I found a solution to install ansible 2.12), unfortunately it terminated with the following error:
....
 Add managed vhost config files.] *********************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: jinja2.exceptions.TemplateRuntimeError: no test named 'true'
failed: [localhost] (item={'listen': '80', 'root': '/var/www/html', 'index': 'index.html index.htm', 'filename': 'alfresco.conf'}) => {"ansible_loop_var": "item", "changed": false, "item": {"filename": "alfresco.conf", "index": "index.html index.htm", "listen": "80", "root": "/var/www/html"}, "msg": "TemplateRuntimeError: no test named 'true'"}

PLAY RECAP ******************************************************************************************************************************************************************
localhost                  : ok=203  changed=14   unreachable=0    failed=1    skipped=174  rescued=0    ignored=0

So, questions are: 

What is causing the error above and how can I install the necesarry prerequisites in Centos7 (7.9) in order to execute the latest alfresco-ansible-deployment.

Thank you in advance for any hint to solve this issue.

**Comment by alxgomz** [comment]
Looks like a wrong version of the jinja lib. That should not happen if you used the requirement.txt file. Can you please send the output of the command below (execution from the python virtualenv:

```shell
pip freeze
```

**Comment by MatthiasBauernberger** [comment]
I did use the requirements.txt file, but before I googled a soltuion to get pip on a fresh Ubuntu 20 LTS installed. Maybe this wasn't correct. Do you have any suggestions about the correct procedure to install the correct pip version (Ubuntu 20 LTS or CentOS7.9 before I use requirement.txt)? I already deleted this machines (were just azure test vms).  

Thank you.

**Comment by alxgomz** [comment]
The documentation @gionn pointed is using python virtualenvwrapper. There are others virtualenv solution in python but the documented procedure should work as long as you have an python version that's at least least 3.8 (so most likely not on centos7, but ubuntu 20 should be ok).
Once you have created the virtualenv using the `mkvirtualenv` command as documented you will have all that's required to install the requirements and generally speaking you can install whatever python package you need without impacting your system.
You don't need to apply any solution googled in some place.

More doc on virtualenvwrapper if needed: https://virtualenvwrapper.readthedocs.io/en/latest/command_ref.html

And the documented procedure: https://github.com/Alfresco/alfresco-ansible-deployment/blob/master/docs/deployment-guide.md#setup-a-control-node

**Comment by alxgomz** [comment]
Of course I didn't mentioned it but if you use a virtualenv you first need to switch to it before playing the playbook otherwise you'll rely on system libs and version instead of the ones installed in the virtualenv

**Comment by MatthiasBauernberger** [comment]
OK, I'll give it another try with Ubuntu 20 LTS. Thank you.

**Comment by MatthiasBauernberger** [comment]
I gave this approach up. There are too many prerequisites: OS, pyhthon(3), ansible. I switched back to use the superb docker-compose script maintained by @aborroy which works for me on Oracle Linux 8.5 flawless. Thank you for your feedback.
