### ISSUE TITLE
jinja2 - vhost config task

### ISSUE THREAD

**Issue by Fikili** [Alfresco/alfresco-ansible-deployment#327]
#### Bug description
Installation of ACS 7.2 using Ansible deployment v2 has several issues. One of them is related to  jinja2 once following command is executed: `$ ansible-playbook playbooks/acs.yml -i inventory_ssh.yml`. Error is mentioned below.

FYI, I am using WSL2 with Ubuntu 20

**Expected behavior:** No error and smooth installation.

#### Target OS

RHEL 8.3

#### Ansible error
```shell
TASK [../roles/nginx : Add managed vhost config files.] ********
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: jinja2.exceptions.TemplateRuntimeError: no test named 'true'
failed: [nginx_1] (item={'listen': '80', 'root': '/usr/share/nginx/html', 'index': 'index.html index.htm', 'filename': 'alfresco.conf'}) => {"ansible_loop_var": "item", "changed": false, "item": {"filename": "alfresco.conf", "index": "index.html index.htm", "listen": "80", "root": "/usr/share/nginx/html"}, "msg": "TemplateRuntimeError: no test named 'true'"}
```

##### ansible --version

```shell
ansible [core 2.12.4]
  config file = /home/alfresco/git/alfresco-ansible-deployment/ansible.cfg
  configured module search path = ['/home/alfresco/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /home/alfresco/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.8.10 (default, Mar 15 2022, 12:22:08) [GCC 9.4.0]
  jinja version = 2.10.1
  libyaml = True
```

##### ansible-config dump --only-changed

```shell
ANSIBLE_PIPELINING(/home/alfresco/git/alfresco-ansible-deployment/ansible.cfg) = True
```

##### ansible-inventory -i your_inventory_file --graph

```shell
@all:
  |--@activemq:
  |  |--activemq_1
  |--@adw:
  |  |--adw_1
  |--@database:
  |  |--database_1
  |--@external:
  |  |--@external_activemq:
  |--@external_activemq:
  |--@nginx:
  |  |--nginx_1
  |--@repository:
  |  |--repository_1
  |--@search:
  |  |--search_1
  |--@syncservice:
  |  |--syncservice_1
  |--@transformers:
  |  |--transformers_1
  |--@ungrouped:
```

**Comment by gionn** [comment]
Hello, your jinja version is pretty old, you can see the version we are testing against in:
https://github.com/Alfresco/alfresco-ansible-deployment/blob/master/requirements.txt#L14

If you follow the [deployment guide](https://github.com/Alfresco/alfresco-ansible-deployment/blob/master/docs/deployment-guide.md#setup-a-control-node) you will see that we suggest to install dependencies via the standard `requirements.txt` and don't rely on what you have preinstalled on the system because every python distribution bundle a jinja2 version depending on how old that distribution is.

Thanks for taking time to open a new issue.

**Comment by Fikili** [comment]
Hi @gionn , thanks. I will check that and let you know.

**Comment by alxgomz** [comment]
Hi @Fikili, 
As a side note, we really encourage you to use python virtualenvs (as described in the link @gionn shared). They make it really easy to move between version of python libraries and ansible versions, by switching from one virtualenv to another and never forces you to overwrite any system library at any point in time. The single requirement is to have a system python version that's 3.8+
If that's not an option, or you think it is not well suited to your needs, I'd be interested to understand why and how we can better address that point

**Comment by Fikili** [comment]
Hi @gionn @alxgomz,
Thanks for your comments, I was able to solve problem with Jinja once I followed the documentation properly. Only part that was done differently is installation of virtual environment for Ubuntu 20 running using WSL. 
My procedure is below:
```
alfresco@XXXX:~/git/alfresco-ansible-deployment $ sudo apt install -y python3-venv
alfresco@XXXX:~/git/alfresco-ansible-deployment $ python3 -m venv alfresco-ansible
alfresco@XXXX:~/git/alfresco-ansible-deployment $ source alfresco-ansible/bin/activate
(alfresco-ansible) alfresco@XXXX:~/git/alfresco-ansible-deployment $
```
However, I still have many other issues and I will create separate issues to track those.
