### ISSUE TITLE
Missing environment variables TOMCAT_HOME

### ISSUE THREAD

**Issue by Fikili** [Alfresco/alfresco-ansible-deployment#330]
#### Bug description

After resolving issues in https://github.com/Alfresco/alfresco-ansible-deployment/issues/328 and not handling errors reported in https://github.com/Alfresco/alfresco-ansible-deployment/issues/329, I can see that Alfresco cannot startup because of missing environment variables.

If I start Alfresco repository by `sudo systemctl start alfresco-content.service`, I get error message visible using `journalctl -xe`: 
```shell
Apr 23 11:46:40 tomcat.sh[31057]: /bin/bash: /bin/catalina.sh: No such file or directory
Apr 23 11:46:40 systemd[1]: alfresco-content.service: Control process exited, code=exited status=127
Apr 23 11:46:40 systemd[1]: alfresco-content.service: Failed with result 'exit-code'.
```

The same error message can be seen if I run startup command directly by alfresco user:
```shell
$ /opt/alfresco/tomcat.sh start
/bin/bash: /bin/catalina.sh: No such file or directory
```

The problem is caused by missing environment variables. If I run part of tomcat.sh manually, I can see that value for "CATALINA_HOME" is empty:
```shell
$ . /etc/opt/alfresco/setenv.sh
$ export CATALINA_HOME=${TOMCAT_HOME}
$ env | grep CATA
CATALINA_HOME=
```

The problem here is caused already by missing "TOMCAT_HOME"

#### Target OS

RHEL 8.3

#### Ansible error

The error is not visible during Ansible deploy but after that once Alfresco repository is started.

#### Ansible context

Same as https://github.com/Alfresco/alfresco-ansible-deployment/issues/328

**Comment by alxgomz** [comment]
Hi @Fikili ,

This is most likely something we introduced recently in master. @gionn told me about the exact same thing on friday and according to him this is something linked with idempotency. So most likely, everything works ok if the playbook works on the first try. But in some cases it may fail after a second/third run...
Do you remember if you had to restart the playbook and if so at what stage it did fail?

**Comment by alxgomz** [comment]
Bug confirmed & introduced by: https://github.com/Alfresco/alfresco-ansible-deployment/commit/d5decf4cef275c5754e1d16ddbac67fd10900736#diff-ac0f65d3b426670bcb415da9b458d4236af17cb17d3e9bb01e86106b13e2828eL55

Now tracked in OPSEXP-1424

**Comment by Fikili** [comment]
Hi @alxgomz,

At the moment, I am not able to run the playbook without issues so it is very likely that issue is related to idempotency. Thanks for tracking that as a new bug.

**Comment by alxgomz** [comment]
Hi @Fikili ,

Can you give https://github.com/Alfresco/alfresco-ansible-deployment/commits/opsexp-1424 a try?
I was hoping to test and merge to master but libreoffice download seem to fail miserably since this morning and tests cannot complete.

**Comment by Fikili** [comment]
Let me try

**Comment by alxgomz** [comment]
Ah yes ofc, triggering the cleanup procedure wil force downloading artifacts again.
On my side I've restarted the tests as the download seems a bit healthier right now 🤞

**Comment by Fikili** [comment]
Hi @alxgomz,

I can confirm that issue is not visible anymore. Thanks for help.
