### ISSUE TITLE
SOLR not working with latest ansible deploy

### ISSUE THREAD

**Issue by mtwallach** [Alfresco/alfresco-ansible-deployment#343]
#### Bug description

The install seems to work fine, however SOLR is not able to access ACS. Errors are:

2022-05-12 14:14:00.011 WARN  (org.alfresco.solr.AlfrescoCoreAdminHandler@72ba28ee_Worker-21) [   ] o.a.s.t.CommitTracker Rollback performed due to ACL Tracker error
java.net.ConnectException: Connection refused (Connection refused)
        at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)

#### Target OS

Ubuntu 20.04

#### Ansible error

No error. SOLR just is unable to communicate to ACS. It could be user of secret but documentation is not very descriptive. What do you have to set and where, in which yml file must you change to use secret?

```shell

```

#### Ansible context

Paste the output of the following commands:

##### ansible --version
```shell
ansible [core 2.12.5]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.8.10 (default, Mar 15 2022, 12:22:08) [GCC 9.4.0]
  jinja version = 2.10.1
  libyaml = True
```

##### ansible-config dump --only-changed
```shell
ANSIBLE_PIPELINING(/home/ubuntu/Installs/alfresco-ansible-deployment-master/ansible.cfg) = True
```

##### ansible-inventory -i your_inventory_file --graph

```shell
@all:
  |--@activemq:
  |  |--@repository:
  |  |  |--localhost
  |--@adw:
  |  |--@repository:
  |  |  |--localhost
  |--@database:
  |  |--@repository:
  |  |  |--localhost
  |--@external:
  |  |--@external_activemq:
  |--@external_activemq:
  |--@nginx:
  |  |--@repository:
  |  |  |--localhost
  |--@repository:
  |  |--localhost
  |--@search:
  |  |--@repository:
  |  |  |--localhost
  |--@syncservice:
  |  |--@repository:
  |  |  |--localhost
  |--@transformers:
  |  |--@repository:
  |  |  |--localhost
  |--@ungrouped:
```

**Comment by mtwallach** [comment]
I can see after running ansible-playbook playbooks/acs.yml -i inventory_local.yml, services are started and SOLR is accessing ACS through nginx. How is that configured? Because if I stop services and restart, SOLR longer seems to be able to connect to ACS

**Comment by gionn** [comment]
> ```shell
>   jinja version = 2.10.1
> ```

can't understand how your playbook run could have completed without any error given that old jinja version (see [latest](https://github.com/Alfresco/alfresco-ansible-deployment/blob/master/requirements.txt#L14) tested) and that another user already reported of that not working https://github.com/Alfresco/alfresco-ansible-deployment/issues/327
