### ISSUE TITLE
alfresco-content-monitored will stop Alfresco if curl is not installed

### ISSUE THREAD

**Issue by Fikili** [Alfresco/alfresco-ansible-deployment#351]
#### Bug description

Ubuntu 20.04 doesn't have `curl` utility installed by default, it is causing that `/opt/alfresco/alfresco-content-monitored-startup.sh` is failing and will stop Alfresco in a few mins after successful startup.

I used the latest code in master branch from 29May2022.

#### Target OS

Ubuntu 20.04 

#### Ansible error

NA

**Comment by Fikili** [comment]
FYI, I used localhost deployment for ACS 7.2.

**Comment by gionn** [comment]
Hello, it may be that your ubuntu 20.04 image is the minimal flavour that doesn't have curl pre-installed, we should handle that.

From which source is your ubuntu 20.04 coming from?

**Comment by Fikili** [comment]
Hi @gionn,
If I recall well, I haven't installed minimal flavour. The image "ubuntu-20.04.2.0-desktop-amd64.iso" has 2.8 GB. It was available on https://ubuntu.com/download/desktop but nowadays it is replaced by LTS 22.04.

**Comment by alxgomz** [comment]
Close with OPSEXP-1505 resolution
