### ISSUE TITLE
"Ensure a list of packages installed" task failed with ansible 2.13

### ISSUE THREAD

**Issue by amberream** [Alfresco/alfresco-ansible-deployment#413]
#### Bug description

I'm installing alfresco community edition 7.2 on CentOS 7 with Python 3.8 and Ansible 2.13.  It fails with the following error:

TASK [../roles/repository : Ensure a list of packages installed] ***************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "It appears that a space separated string of packages was passed in as an argument. To operate on several packages, pass a comma separated string of packages or a list of packages."}

The task in roles/repository/tasks/main.yml looks like:
- name: Ensure a list of packages installed
  become: true
  package:
    name: "{{ utils_repo }} + {{ utils_storage[cs_storage.type | default('tmpfs')] }}"
    state: present

#### Target OS

CentOS 7

#### Ansible error

```shell
TASK [../roles/repository : Ensure a list of packages installed] ***************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "It appears that a space separated string of packages was passed in as an argument. To operate on several packages, pass a comma separated string of packages or a list of packages."}

```

#### Ansible context

Paste the output of the following commands:

##### ansible --version

```shell
ansible [core 2.13.3]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /root/.local/lib/python3.8/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /root/.local/bin/ansible
  python version = 3.8.10 (default, Aug 24 2022, 18:42:19) [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]
  jinja version = 3.0.3
  libyaml = True

```

##### ansible-config dump --only-changed

```shell

```

##### ansible-inventory -i your_inventory_file --graph

```shell
@all:
  |--@activemq:
  |  |--@repository:
  |  |  |--localhost
  |--@adw:
  |  |--@repository:
  |  |  |--localhost
  |--@database:
  |  |--@repository:
  |  |  |--localhost
  |--@external:
  |  |--@external_activemq:
  |--@external_activemq:
  |--@nginx:
  |  |--@repository:
  |  |  |--localhost
  |--@repository:
  |  |--localhost
  |--@search:
  |  |--@repository:
  |  |  |--localhost
  |--@syncservice:
  |  |--@repository:
  |  |  |--localhost
  |--@transformers:
  |  |--@repository:
  |  |  |--localhost
  |--@ungrouped:

```

**Comment by amberream** [comment]
As a work around I deleted that task, but it would be nice to fix it.

**Comment by gionn** [comment]
Hello,

> Ansible 2.13

we are currently testing the playbook with Ansible [2.12.x](https://github.com/Alfresco/alfresco-ansible-deployment/blob/master/Pipfile#L7), so the first suspect could be that in 2.13 it have been deprecated the support to provide the list of packages as a space separated string.

Can you try again after downgrading ansible to 2.12.8?

Please be aware also that in latest master we recently switched from plain requirements.txt to pipenv that should prevents this kind of issues, if you want to [give it a try](https://github.com/Alfresco/alfresco-ansible-deployment/blob/master/docs/deployment-guide.md#setup-runtime-environment).

**Comment by gionn** [comment]
The referenced [PR build](https://github.com/Alfresco/alfresco-ansible-deployment/runs/8012646023?check_suite_focus=true#step:7:920) confirms that the issue is caused by ansible 2.13, let's see if there is a way to make both versions happy.

**Comment by gionn** [comment]
We have got mostly green builds with the now updated development version, for the future we are going to setup a dedicated build for making sure that the playbook will works with the upcoming ansible-core versions.

Thanks for reporting!

**Comment by amberream** [comment]
Ok great.  Btw, I didn't see anywhere in the installation instructions how to restart the alfresco service.  It doesn't seem to start up automatically when I reboot the machine.  Any tips?

I followed the instructions here for a single machine: https://docs.alfresco.com/content-services/community/install/ansible/#local-installation
