### ISSUE TITLE
7.2.x extra vars not included in 2.1 release.

### ISSUE THREAD

**Issue by mckeithyb-ssl** [Alfresco/alfresco-ansible-deployment#498]
#### Bug description

The tagged scripts for the 2.1 release do not include the 7.2.x 'extra vars' script. The 7.1.x script as the name suggests is only configured to download 7.1.1. 

The hyland documentation links to version 2.0 (https://docs.alfresco.com/content-services/latest/install/ansible/ -> https://nexus.alfresco.com/nexus/service/local/repositories/releases/content/org/alfresco/alfresco-ansible-deployment/2.0.0/alfresco-ansible-deployment-2.0.0.zip), so this is what most users will use, but it does not download 7.2.x components.

It was found that modifying the 7.1.x to download 7.2 components, more changes were necessary to support the new solr 'secret' functionality. I made my own changes to fix the solr config issue so I could create a PR, but I wonder if this is just down to a problem with tagging in git hub. I notice that the branch labeled next/7.3 contains files for 7.2.x. which I have yet to review.

**Comment by mckeithyb-ssl** [comment]
Thanks for the reply, ah ok, I didn’t spot the implication that the ‘extra vars’ scripts were intended to be used for previous versions only, and there isn’t a dedicated file for the latest. It seems obvious now!

I ended up modifying the 2.0.0 scripts for our customer,  and mostly things went fine but I had a problem where solr wasn’t starting up to use the shared secret when alfresco.secureComms=secret in solrcore.properties

I had to add 

`SOLR_OPTS="$SOLR_OPTS -Dalfresco.secureComms=secret -Dalfresco.secureComms.secret={{ reposearch_shared_secret }}" `

to 

`roles/search/templates/solr.in.sh `

I didn’t like hardcoding that parameter – It should have been picked up from solrcore.properties, but I think that might be a known issue in ASS.

We also had to make sure that the FQDN was used everywhere rather than a resolved IP address, as the customer intended to switch the IP addresses of the server after go-live.

**Comment by gionn** [comment]
> I ended up modifying the 2.0.0 scripts for our customer, and mostly things went fine but I had a problem where solr wasn’t starting up to use the shared secret when alfresco.secureComms=secret in solrcore.properties

`alfresco.secureComms.secret` is handled in the startup script [solr.sh](https://github.com/Alfresco/alfresco-ansible-deployment/blob/master/roles/search/templates/solr.sh.j2#L8) and won't startup without it so it must be for some other reason in your case.

> We also had to make sure that the FQDN was used everywhere rather than a resolved IP address, as the customer intended to switch the IP addresses of the server after go-live.

IP addresses are usually gathered from the inventory file itself, so you either need to re-run the playbook on the final infrastructure after the IP change or make sure that dns resolution works and use fqdn in the inventory.
