### ISSUE TITLE
alfresco-ansible-deployment: community-extra-vars.yml (release 7.3)

### ISSUE THREAD

**Issue by rubisher** [Alfresco/alfresco-ansible-deployment#521]
#### Bug description

In the community-extra-vars.yml extra var definition, a repository is referring to an 'enterprise' one?  

#### Target OS

RHEL 8 (Actually Almalinux 8)

#### Ansible error

iirc couldn't open "{{ nexus_repository.enterprise_releases }}/integrations/alfresco-googledrive-repo-community"
(sorry I lost the accurate message but not be able to rerun right now :()

```shell

```

#### Ansible context

Paste the output of the following commands:

##### ansible --version

```
└─$ pipenv run ansible --version
ansible [core 2.12.10]
  config file = /home/jlst/Ansible/alfresco-ansible-deployment-2.2.0/ansible.cfg
  configured module search path = ['/home/jlst/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/jlst/.local/share/virtualenvs/alfresco-ansible-deployment-2.2.0-uRpBk9AW/lib/python3.9/site-packages/ansible
  ansible collection location = /home/jlst/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/jlst/.local/share/virtualenvs/alfresco-ansible-deployment-2.2.0-uRpBk9AW/bin/ansible
  python version = 3.9.13 (main, Nov 27 2022, 12:32:52) [GCC 12.2.0]
  jinja version = 3.1.2
  libyaml = True


```

##### ansible-config dump --only-changed

```
└─$ pipenv run ansible-config dump --only-changed
ANSIBLE_PIPELINING(/home/jlst/Ansible/alfresco-ansible-deployment-2.2.0/ansible.cfg) = True


```

##### ansible-inventory -i your_inventory_file --graph

```
└─$ pipenv run ansible-inventory -i my_inventory_ssh.yml --graph
@all:
  |--@activemq:
  |  |--activemq_1
  |--@adw:
  |  |--adw_1
  |--@database:
  |  |--database_1
  |--@elasticsearch:
  |--@external:
  |  |--@external_activemq:
  |  |--@external_elasticsearch:
  |  |--@other_repo_clients:
  |--@external_activemq:
  |--@external_elasticsearch:
  |--@nginx:
  |  |--nginx_1
  |--@other_repo_clients:
  |--@repository:
  |  |--repository_1
  |--@search:
  |  |--search_1
  |--@search_enterprise:
  |--@syncservice:
  |  |--syncservice_1
  |--@transformers:
  |  |--transformers_1
  |--@trusted_resource_consumers:
  |  |--@adw:
  |  |  |--adw_1
  |  |--@nginx:
  |  |  |--nginx_1
  |  |--@other_repo_clients:
  |  |--@repository:
  |  |  |--repository_1
  |--@ungrouped:


```

**Comment by gionn** [comment]
Thanks @rubisher for reporting, it looks like it slipped thru because the community integration tests are still injecting nexus credentials due to a bug in the GH workflow.

Good catch!

**Comment by rubisher** [comment]
Just to be sure, I re-run the mater and noticed a similar failure to [search_1] & [transformers_1] which also failed to download from 'public' tree
fatal: [search_1]: FAILED! => {
    "msg": "An unhandled exception occurred while running the lookup plugin 'url'. Error was a <class 'ansible.errors.AnsibleError'>, original message: Received HTTP error for https://artifacts.alfresco.com/nexus/content/groups/private/org/alfresco/alfresco-search-services/2.0.5.1/alfresco-search-services-2.0.5.1.zip.sha1 : HTTP Error 401: Unauthorized. Received HTTP error for https://artifacts.alfresco.com/nexus/content/groups/private/org/alfresco/alfresco-search-services/2.0.5.1/alfresco-search-services-2.0.5.1.zip.sha1 : HTTP Error 401: Unauthorized"
}

Easily work around with local var file:
search:
  artifact_name: alfresco-search-services
  repository: "{{ nexus_repository.releases }}"
  version: 2.0.5.1
transform:
  artifact_name: alfresco-transform-core-aio-boot
  repository: "{{ nexus_repository.releases }}"
  version: 2.5.7

downloads:
  acs_zip_url: >-
    {{ acs.repository }}/{{ acs.artifact_name }}/{{ acs.version }}/{{ acs.artifact_name }}-{{ acs.version }}.zip
  acs_zip_sha1_checksum_url: >-
    {{ acs.repository }}/{{ acs.artifact_name }}/{{ acs.version }}/{{ acs.artifact_name }}-{{ acs.version }}.zip.sha1
  search_zip_url: >-
    {{ search.repository }}/{{ search.artifact_name }}/{{ search.version }}/{{ search.artifact_name }}-{{ search.version }}.zip
  search_zip_sha1_checksum_url: >-
    {{ search.repository }}/{{ search.artifact_name }}/{{ search.version }}/{{ search.artifact_name }}-{{ search.version }}.zip.sha1
  transform_jar_url: >-
    {{ transform.repository }}/{{ transform.artifact_name }}/{{ transform.version }}/{{ transform.artifact_name }}-{{ transform.version }}.jar
  transform_jar_sha1_checksum_url: >-
    {{ transform.repository }}/{{ transform.artifact_name }}/{{ transform.version }}/{{ transform.artifact_name }}-{{ transform.version }}.jar.sha1

Thx again for help,
Rudy

**Comment by gionn** [comment]
Thanks for the update, fixing the integration test actually exposed a similar issue in the search role indeed, PR to address the issues should be merged soon.

**Comment by rubisher** [comment]
Hey Gionn,

Sorry for late answer but I confirm that this works ;)
But don't yet fix this Failure message "We couldn't create user ." when using the fqdn of the box in place of localhost?

Thx a lot again for help,
Rudy
