### ISSUE TITLE
dependencies-rpm.yml  -- warn: false is an unsupported parameter for command module

### ISSUE THREAD

**Issue by SoMoney** [Alfresco/alfresco-ansible-deployment#540]
#### Bug description
Quick fix.  I commented the warn: false line out of dependencies-rpm.yml and the play ran just fine after that.

#### Target OS
```
Centos 7
ansible [core 2.14.2]
Python 3.9.9
```

#### Ansible error

```
TASK [../roles/transformers : Install LibreOffice RPMs] *****************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Unsupported parameters for (ansible.legacy.command) module: warn. Supported parameters include: _raw_params, _uses_shell, argv, chdir, creates, executable, removes, stdin, stdin_add_newline, strip_empty_ends."}

PLAY RECAP **************************************************************************************************************************************************************************************
localhost                  : ok=86   changed=46   unreachable=0    failed=1    skipped=49   rescued=0    ignored=0   


```

#### Ansible context

Paste the output of the following commands:

##### ansible --version

```
ansible [core 2.14.2]
  config file = /opt/alfresco-ansible-deployment/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /root/.local/lib/python3.9/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /bin/ansible
  python version = 3.9.9 (main, Feb  3 2023, 10:11:30) [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)] (/usr/local/bin/python3)
  jinja version = 3.1.2
  libyaml = True
```

##### ansible-config dump --only-changed

```
ANSIBLE_PIPELINING(/opt/alfresco-ansible-deployment/ansible.cfg) = True
CONFIG_FILE() = /opt/alfresco-ansible-deployment/ansible.cfg

```

**Comment by gionn** [comment]
Hello, same issue of https://github.com/Alfresco/alfresco-ansible-deployment/issues/534

you are using the latest ansible that is currently unsupported by the playbook and you are not using pipenv that is the current way we deal with dependencies that should prevent any headaches regarding that.

Instructions to follow are detailed in the [deployment guide](https://github.com/Alfresco/alfresco-ansible-deployment/blob/master/docs/deployment-guide.md#setup-runtime-environment).

Let mew know if you face any issue with that or please close this issue.

**Comment by SoMoney** [comment]
Hey thanks for the heads up.  Went back into my install steps and saw galaxy.ansible.com/api timed out so it didn't complete the requirements.yml.    It was a TLS decryption issue on my Sophos Firewall.

CLOSED!
