### ISSUE TITLE
Verify accuracy of documentation statement

### ISSUE THREAD

**Issue by morgan-patou** [Alfresco/alfresco-ansible-deployment#585]
#### Description

Hello, could you please help to check the accuracy of [deployment-guide.md line 267](https://github.com/Alfresco/alfresco-ansible-deployment/blob/7764af09c54162150636679f5c290fc2abefa8d2/docs/deployment-guide.md?plain=1#L267) as well as [deployment-guide.md line 271](https://github.com/Alfresco/alfresco-ansible-deployment/blob/7764af09c54162150636679f5c290fc2abefa8d2/docs/deployment-guide.md?plain=1#L271)?

line 267: it's written port 80 for the ADW, shouldn't this be 8880 instead? (or maybe it should be removed completely since ADW needs to be on the Nginx host at the moment (unless this was fixed/changed?) and therefore communications would only happen locally from Nginx to 8880 port of ADW).

line 271: the playbook `prerequisite-checks.yml` is currently trying to connect from the repository host to the SFS / TRouter ports but according to the doc, these 2 ports are only used locally. Do you know what would be the correct statement? I assume that the 3 ports should be accessible from the Repository since we configure these details on the `alfresco-global.properties` but I'm not certain.

I'm currently writing some code to handle the firewall configuration and would appreciate some help with these details, to finish the checks and possibly fix the missing elements in the doc/existing playbooks as well.

#### Target OS

All

#### Ansible error

No specific errors, just some documentation and potentially some playbook adaptation needed depending on the correct statement.

Thanks for the check and the feedback!

**Comment by gionn** [comment]
> line 267: it's written port 80 for the ADW, shouldn't this be 8880 instead? (or maybe it should be removed completely since ADW needs to be on the Nginx host at the moment (unless this was fixed/changed?) and therefore communications would only happen locally from Nginx to 8880 port of ADW).

you are right, adw role expose 8880 and expect to be reachable there by nginx node.

I am not aware on any issues when nginx and adw are not on the same node, but I know that a common deployment choice is to have them on the same node.

> line 271: the playbook `prerequisite-checks.yml` is currently trying to connect from the repository host to the SFS / TRouter ports but according to the doc, these 2 ports are only used locally. Do you know what would be the correct statement? I assume that the 3 ports should be accessible from the Repository since we configure these details on the `alfresco-global.properties` but I'm not certain.

I am not sure at this point how much we can trust that playbook given that is not part of any integration tests and may be a good idea to hook it at the end. I will give it a try.

**Comment by gionn** [comment]
maybe @alxgomz can give more insights on the second point

**Comment by alxgomz** [comment]
Yes indeed the 3 ATS components need to be accessible from an enterprise repo which needs to act as  an http client to the tengine,  trouter & sfs servers. A community repo can only use "localtransformers" so it just talks to the tengines.

**Comment by morgan-patou** [comment]
> you are right, adw role expose 8880 and expect to be reachable there by nginx node.
> 
> I am not aware on any issues when nginx and adw are not on the same node, but I know that a common deployment choice is to have them on the same node.

While browsing the doc a few week ago, I saw [this line](https://github.com/Alfresco/alfresco-ansible-deployment/blob/7764af09c54162150636679f5c290fc2abefa8d2/docs/deployment-guide.md?plain=1#L907). It says that ADW can only be deployed on the same node as Nginx for now, hence my comment. Maybe it's not correct anymore?


> > line 271: the playbook `prerequisite-checks.yml` is currently trying to connect from the repository host to the SFS / TRouter ports but according to the doc, these 2 ports are only used locally. Do you know what would be the correct statement? I assume that the 3 ports should be accessible from the Repository since we configure these details on the `alfresco-global.properties` but I'm not certain.
> 
> I am not sure at this point how much we can trust that playbook given that is not part of any integration tests and may be a good idea to hook it at the end. I will give it a try.

From the tests I did last week, it seems to be working mostly. I had to do some changes here and there but not much. I was planning to include some change to this file in a PR, including the setup of the firewall. I think it would make more sense to setup the firewall in the acs playbook and keep this check playbook separately, in case someone wants to do a verification.

**Comment by morgan-patou** [comment]
Is the [line 266](https://github.com/Alfresco/alfresco-ansible-deployment/blob/7764af09c54162150636679f5c290fc2abefa8d2/docs/deployment-guide.md?plain=1#L266) from the documentation also correct? If I look at the prerequisite playbook [line 27](https://github.com/Alfresco/alfresco-ansible-deployment/blob/7764af09c54162150636679f5c290fc2abefa8d2/playbooks/prerequisite-checks.yml#L27), it appears that the connection from the Repository to the SyncService is tested no? So does the repository need to connect to the SyncService as well? I never used this syncservice so not sure about the connection details needed.

**Comment by morgan-patou** [comment]
> Is the [line 266](https://github.com/Alfresco/alfresco-ansible-deployment/blob/7764af09c54162150636679f5c290fc2abefa8d2/docs/deployment-guide.md?plain=1#L266) from the documentation also correct? If I look at the prerequisite playbook [line 27](https://github.com/Alfresco/alfresco-ansible-deployment/blob/7764af09c54162150636679f5c290fc2abefa8d2/playbooks/prerequisite-checks.yml#L27), it appears that the connection from the Repository to the SyncService is tested no? So does the repository need to connect to the SyncService as well? I never used this syncservice so not sure about the connection details needed but the documentation only mention that nginx would communicate with the syncservice, not the repo.

I assumed that the correct one was the playbook, so I added the information on the doc that syncservice needs to be accessible from the repository.
See PR #589 for the firewall part and #607 for the doc update + network checks

**Comment by gionn** [comment]
Fixed in https://github.com/Alfresco/alfresco-ansible-deployment/pull/607

Thanks @morgan-patou for your kind efforts 🎉
