### ISSUE TITLE
Deploy error in roles/repository: The task includes an option with an undefined variable

### ISSUE THREAD

**Issue by guilloking** [Alfresco/alfresco-ansible-deployment#714]
#### Ansible error

TASK [../roles/repository : Validating arguments against arg spec 'main' - Main entrypoint for the repository role] *************************************************************
fatal: [localhost]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: {'db': {'url': \"{{ repo_db_url if repo_db_url else 'jdbc:postgresql://' + db_host + ':' + ports_cfg.postgres.sql | string + '/' + repo_db_name }}\", 'driver': '{{ repo_db_driver }}', 'username': '{{ repo_db_username }}', 'password': '{{ repo_db_password }}'}, 'alfresco': {'host': \"{{ fqdn_alfresco | default(known_urls[0] | urlsplit('hostname')) | default(nginx_host) }}\", 'port': '{{ acs_play_port }}', 'protocol':'{{ acs_play_proto }}', 'cluster': {'enabled': \"{{ (groups['repository'] | length > 1 and not (cluster_keepoff | bool)) | lower }}\"}}, 'share': {'host': \"{{ fqdn_alfresco | default(known_urls[0] | urlsplit('hostname')) | default(nginx_host) }}\", 'port': '{{ acs_play_port }}', 'protocol': '{{ acs_play_proto }}'}, 'messaging': {'broker': {'url': 'failover:({{ activemq_transport }}://{{ activemq_host }}:{{ ports_cfg.activemq[activemq_protocol] }})?timeout=3000', 'username': '{{ activemq_username }}', 'password': '{{ activemq_password }}'}}, 'aos': {'baseUrlOverwrite': '{{ acs_play_proto }}://{{ fqdn_alfresco | default(nginx_host) }}:{{ acs_play_port }}/alfresco/aos'}}: list object has no element 0. list object has no element 0. {'db': {'url': \"{{ repo_db_url if repo_db_url else 'jdbc:postgresql://' + db_host + ':' + ports_cfg.postgres.sql | string + '/' + repo_db_name }}\", 'driver': '{{ repo_db_driver }}', 'username': '{{ repo_db_username }}', 'password': '{{ repo_db_password }}'}, 'alfresco': {'host': \"{{ fqdn_alfresco | default(known_urls[0] | urlsplit('hostname')) | default(nginx_host) }}\", 'port': '{{ acs_play_port }}', 'protocol': '{{ acs_play_proto }}', 'cluster': {'enabled': \"{{ (groups['repository'] | length > 1 and not (cluster_keepoff | bool)) | lower }}\"}}, 'share': {'host': \"{{ fqdn_alfresco | default(known_urls[0] | urlsplit('hostname')) | default(nginx_host) }}\", 'port': '{{ acs_play_port }}', 'protocol': '{{ acs_play_proto }}'}, 'messaging': {'broker': {'url': 'failover:({{ activemq_transport }}://{{ activemq_host }}:{{ ports_cfg.activemq[activemq_protocol] }})?timeout=3000', 'username': '{{ activemq_username }}', 'password': '{{ activemq_password }}'}}, 'aos': {'baseUrlOverwrite': '{{ acs_play_proto }}://{{ fqdn_alfresco | default(nginx_host) }}:{{ acs_play_port }}/alfresco/aos'}}: list object has no element 0. list object has no element 0. {'db': {'url': \"{{ repo_db_url if repo_db_url else 'jdbc:postgresql://' + db_host + ':' + ports_cfg.postgres.sql | string + '/' + repo_db_name }}\", 'driver': '{{ repo_db_driver }}', 'username': '{{ repo_db_username }}', 'password': '{{ repo_db_password }}'}, 'alfresco': {'host': \"{{ fqdn_alfresco | default(known_urls[0] | urlsplit('hostname')) | default(nginx_host) }}\", 'port': '{{ acs_play_port}}', 'protocol': '{{ acs_play_proto }}', 'cluster': {'enabled': \"{{ (groups['repository'] | length > 1 and not (cluster_keepoff | bool)) | lower }}\"}}, 'share': {'host': \"{{fqdn_alfresco | default(known_urls[0] | urlsplit('hostname')) | default(nginx_host) }}\", 'port': '{{ acs_play_port }}', 'protocol': '{{ acs_play_proto }}'}, 'messaging': {'broker': {'url': 'failover:({{ activemq_transport }}://{{ activemq_host }}:{{ ports_cfg.activemq[activemq_protocol] }})?timeout=3000', 'username': '{{ activemq_username }}', 'password': '{{ activemq_password }}'}}, 'aos': {'baseUrlOverwrite': '{{ acs_play_proto }}://{{ fqdn_alfresco | default(nginx_host) }}:{{ acs_play_port }}/alfresco/aos'}}: list objecthas no element 0. list object has no element 0. {'db': {'url': \"{{ repo_db_url if repo_db_url else 'jdbc:postgresql://' + db_host + ':' + ports_cfg.postgres.sql | string + '/'+ repo_db_name }}\", 'driver': '{{ repo_db_driver }}', 'username': '{{ repo_db_username }}', 'password': '{{ repo_db_password }}'}, 'alfresco': {'host': \"{{ fqdn_alfresco | default(known_urls[0] | urlsplit('hostname')) | default(nginx_host) }}\", 'port': '{{ acs_play_port }}', 'protocol': '{{ acs_play_proto }}', 'cluster': {'enabled': \"{{ (groups['repository'] | length > 1 and not (cluster_keepoff | bool)) | lower }}\"}}, 'share': {'host': \"{{ fqdn_alfresco | default(known_urls[0] | urlsplit('hostname')) | default(nginx_host) }}\", 'port': '{{ acs_play_port }}', 'protocol': '{{ acs_play_proto }}'}, 'messaging': {'broker': {'url': 'failover:({{ activemq_transport }}://{{ activemq_host }}:{{ ports_cfg.activemq[activemq_protocol] }})?timeout=3000', 'username': '{{ activemq_username }}', 'password': '{{ activemq_password }}'}}, 'aos': {'baseUrlOverwrite': '{{ acs_play_proto }}://{{ fqdn_alfresco | default(nginx_host) }}:{{ acs_play_port }}/alfresco/aos'}}: list object has no element 0. list object has no element 0"}

**Comment by alxgomz** [comment]
Hi @guilloking ,

Did you defined the `known_urls` list?

**Comment by AlgoJerViA** [comment]
I'm running into the same problem too.
Is not known_urls defined in inventory_local.yml by default?

...


---
all:
  vars:
    ansible_connection: local
  children:
    repository:
      vars:
        known_urls:
          - http://localhost/share
          - https://localhost/share
      hosts:
        localhost:
    database:
      children:
        repository:

....

**Comment by alxgomz** [comment]
Yes it is but I suspect it gets overridden by the group_var/repository.yaml file that sets it by default as an empty list.
Other inventories do not have this preset `known_urls` as it cannot be predicted. Such default only makes sense if acs is really running on localhost.I'm curious: Are you runnign the playbook against your local host or against a VM running on your machine (maybe using the vagrant provided example)?

**Comment by AlgoJerViA** [comment]
I'm running in a VM but not using Vagrant.
This is just some early testing I'm doing.

**Comment by alxgomz** [comment]
internal tracking OPSEXP-2406

**Comment by alxgomz** [comment]
will be released in 2.4.1 shortly
